# Generated by Django 3.1.6 on 2021-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_d_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('mgr', models.CharField(max_length=10)),
                ('hiredate', models.DateTimeField(verbose_name='更新时间')),
                ('sal', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
            },
        ),
    ]
