# Generated by Django 3.1.6 on 2021-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_d_emp',
            name='hiredate',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
    ]
