# Generated by Django 3.1.6 on 2021-02-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0002_auto_20210209_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_d_hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.CharField(max_length=5, verbose_name='满意度')),
                ('last_evaluation', models.CharField(max_length=5, verbose_name='最后评分')),
                ('number_project', models.CharField(max_length=5, verbose_name='项目数量')),
                ('average_monthly_hours', models.CharField(max_length=5, verbose_name='平均月工作时长')),
                ('time_spend_company', models.CharField(max_length=5, verbose_name='工作时间')),
                ('Work_accident', models.CharField(max_length=5, verbose_name='工作事故')),
                ('left', models.CharField(max_length=2, verbose_name='是否离职')),
                ('promotion_last_5years', models.CharField(max_length=2, verbose_name='5年晋升')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('salary', models.CharField(max_length=20, verbose_name='工资水平')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
            },
        ),
        migrations.DeleteModel(
            name='tbl_d_emp',
        ),
    ]
